### PR TITLE
Add physics.control as a valid submodule

### PR DESCRIPTION
**Pull request by namannimmo10**

### CODE REVIEW

**Comment by asmeurer** [comment]
Can you reference the PR this is being added in?

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy-bot/pull/88 should fix the test failures.

**Comment by namannimmo10** [comment]
> Can you reference the PR this is being added in?

https://github.com/sympy/sympy/pull/19390
For now, I have added NO ENTRY in the release notes.

**Comment by asmeurer** [comment]
Is it still open whether or not this will be the name of the module, or is it decided? If it is decided, we can merge this so that you can add an entry when that PR is merged.

**Comment by namannimmo10** [comment]
Yes, it is decided that the name of the module would be physics.control. There's also a label named after it there.

**Comment by asmeurer** [comment]
OK, this has been deployed. You can add a release notes entry for the control package now.

**Pull request merged**
