### PR TITLE
Start writing tests for the webapp

### LINKED ISSUE #6: Tests for the webapp
Right now we have tests for the parts that parse the pull request description and edit the changelog, but there are no tests for the webapp logic. We should add some. I don't know what the best way to test it is. If anyone knows, let me know.

### PR DESCRIPTION
**Pull request by asmeurer**
These are based on tests from https://github.com/python/bedevere

Fixes #6.

### CODE REVIEW

**Comment by certik** [comment]
Perfect, I think this is the way to go. Once things are robustly tested, then others can easily fix or improve things without having to worry of breaking something.

**Comment by asmeurer** [comment]
For testing updating the wiki, instead of trying to mock subprocess, I've just made a test that updates the wiki on this repo https://github.com/sympy/sympy-bot/wiki/Release-Notes-Tests. It only runs on Travis. I've added a guide to the bottom of the README on how to make and add the token needed for the test to run. This does mean that the test can only be run on Travis for branches on this repo (no PRs from forks), so if any future PR modifies that code, the branch should be pushed up to this repo to check that it works before merging.

**Comment by certik** [comment]
@asmeurer can you document that (your last comment) somewhere? So that people know what to do.

**Comment by asmeurer** [comment]
I put it in the README. Or do you mean something else?

**Pull request merged**
